### ISSUE TITLE
[mozbitbar-48] support setting attributes and starting a test in one method

### ISSUE THREAD

**Issue by worldomonation** [worldomonation/mozbitbar#106]
Add ability, should the user choose, to invoke test runs by just calling start_test_runs and setting some variables there.

**Comment by worldomonation** [comment]
```
- action: one_method_to_rule_all
  arguments:
    device_group_name: something
    test_run_name: something else
    additional_params: None
```
